version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g serverless

  build:
    commands:
      - npm run type-check
      - npm run lint
      - npm run test

  post_build:
    commands:
      - serverless deploy --stage $STAGE

artifacts:
  files:
    - '**/*'
  base-directory: '.' 